#!/bin/bash

if [ -d "build" ]; then
  rm -r build/*
else
  mkdir build
fi
cd build

wget https://mpi4py.googlecode.com/files/mpi4py-1.3.tar.gz
tar xzvf mpi4py-1.3.tar.gz
cd mpi4py-1.3

module purge
module load python/2.7.2 numpy/1.6.1 mpi-tor/openmpi-1.4.5_gcc-4.4.6 matlab/r2011b

echo -e '
# ACISS OPENMPI
# ----------------
[aciss_openmpi]
mpi_dir              = /usr/local/packages/openmpi/1.4_gcc-4.4-tm
mpicc                = %(mpi_dir)s/bin/mpicc
mpicxx               = %(mpi_dir)s/bin/mpicxx
#include_dirs         = %(mpi_dir)s/include
#libraries            = mpi
library_dirs         = %(mpi_dir)s/lib
runtime_library_dirs = %(library_dirs)s' >> mpi.cfg

python setup.py build --mpi=aciss_openmpi
python setup.py install --user

cd ../../

echo -e '\n\n******************************************************************'
echo '                       ENVIRONMENT SETUP                          '
echo '******************************************************************'
echo -e '\nPlease set the MATLABYRINTH environment variable.  For example,'
echo -e '\texport MATLABYRINTH='$PWD'\n'

echo -e 'Then add MATLAByrinth to your path:'
echo -e '\texport PATH=$PATH:$MATLABYRINTH/bin\n'

echo 'If it does not already exist, create a Matlab startup file:'
echo -e '\t~/Documents/MATLAB/startup.m'
echo 'and append this line to the startup.m file:'
echo -e '\taddpath '$PWD'/src/matlab\n'

echo -e 'Refer to the README to see how to test the installation.\n'

