#!/usr/bin/env python

import socket

HOST = "localhost"
PORT = 11098

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((HOST, PORT))

print "send: hey_server\n", 
sock.sendall("hey_server\n")

data = sock.recv(1024)
print "received: " + data

if ( data == "hi client\n" ):
  print "send: bye_server"
  sock.sendall("bye_server\n")
  data = sock.recv(1024)
  print "received: " + data

  if (data == "bye client}\n"):
    sock.close()
    print "Socket closed"
