#!/usr/bin/env python

import sys
import subprocess

if (len(sys.argv) != 2):
  exit('Please tell me the number of processes you want: "launch-interative-matlabyrinth <num_workers+1>"')

print sys.argv[1]

subprocess.call('module purge', shell=True)
subprocess.call('module load python matlab', shell=True)
subprocess.call('module load mpi-tor/openmpi-1.4.5_gcc-4.4.6', shell=True)

subprocess.call('mpiexec --mca btl_tcp_if_include eth0 -np ' + sys.argv[1] + ' python ./MATLAByrinth.py', shell=True)
